package com.easyjojo.model1.models.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

@Data
@TableName("kdpa_sub_acct")
public class Kdpa_Sub_Acct implements Serializable {

    private static final long serialVersionUID = 1L;

    private String lglPernCode;
    private String custNum;
    private String lbltyAcctNum;
    private String subAcctSerlNum;
    private String subAcctNickNm;
    private String custAcctNm;
    private String custAcctNum;
    private String custTp;
    private String prodCode;
    private String termDmdFlg;
    private String dmdAcctClasf;
    private String ccyCodeNum;
    private String deptPrd;
    private String matuDt;
    private String strtIntCalnDt;
    private String intlStrtIntCalnDt;
    private String intlMatuDt;
    private String acctVldPrd;
    private String balGenlLedgerSycrzFlg;
    private String busiAcctgCode;
    private String acctBlgdOrg;
    private String balLatelyUpdDt;
    private BigDecimal acctDeptBal;
    private BigDecimal lastDyDeptBal;
    private BigDecimal acctFltBal;
    private BigDecimal lastDyFltBal;
    private BigDecimal acctOvdfBal;
    private BigDecimal lastDyOvdfBal;
    private String vrfyCode;
    private String deptCatg;
    private String firstDeptDt;
    private String lastBusiDt;
    private BigDecimal openAcctAmt;
    private BigDecimal maxRtanBal;
    private BigDecimal minRtanBal;
    private String deptCtrlWay;
    private String drawCtrlWay;
    private String subAcctSte;
    private String subAcctFormSte;
    private String subAcctFormDt;
    private String acctProtRltnpFlg;
    private String agrmtProdFlg;
    private String agrmtProdType;
    private String wthrPrecsMetal;
    private String alwOvdfFlg;
    private String intPymtWay;
    private String rlvcVchrFlg;
    private String cheqRcpnFlg;
    private String dblZeroAcctFlg;
    private String profitCentr;
    private String mrgnDeptFlg;
    private String asgnDrcn;
    private String unuseSlipNum;
    private String taxCalnFlg;
    private String intTaxCode;
    private String intraBankRcevIntFlg;
    private String intTrfrInAcctNum;
    private String intTrfrInAcctCcy;
    private String intTrfrInAcctNm;
    private String intTrfrInBankCode;
    private String intTrfrInBankNm;
    private BigDecimal alrdyPayInt;
    private BigDecimal alrdyWthldIntTax;
    private BigDecimal thisYrPayInt;
    private BigDecimal thisYrWthldIntTax;
    private BigDecimal lastYrPayInt;
    private BigDecimal lastYrWthldIntTax;
    private String btchGrpNum;
    private String openAcctChnl;
    private String openAcctOrg;
    private String openAcctDt;
    private String cnclAcctChnl;
    private String cnclAcctOrg;
    private String cnclAcctDt;
    private Long curUnusedSerlNum;
    private String acctSteFld;
    private String txnLglPernCode;
    private String mntncTlr;
    private String mntncOrg;
    private String mntncDt;
    private String mntncTm;
    private Long tmstp;
    private String dataCreaTm;
    private String affrSte;
    private String glblAffrRungNum;
    private String affrSteUpdNum;
    private String wthldIntTaxFlg;
    private String preCnclAcctDt;
    private BigDecimal acctBal;
    private BigDecimal lastDyAcctBal;
    private String prodGrpCode;
    private String volTaxPymtFlg;
    private String dblZeroAccDt;
    private String lastDeptDt;
    private String lastWthdlDt;
    private BigDecimal lastDeptAmt;
    private BigDecimal lastWthdlAmt;
    private String intAwrdCode;
    private String intAwrdEffDt;
    private BigDecimal tenorPaidInt;
    private BigDecimal tenorWthldIntTax;
    private BigDecimal aprvEncLmt;
    private BigDecimal usedEncLmt;
    private String encLmtUpdDt;
    private String cpstnAcctFlg;
    private String acctPlegFlg;
    private BigDecimal tdyCashDeptAmt;
    private BigDecimal tdyDeptAmt;
    private BigDecimal tdyWthdlAmt;
    private BigDecimal avaiEncBal;
    private BigDecimal ldyDeptAmt;
    private BigDecimal ldyWthdlAmt;
    private String sysLastMntncDt;
    private String latelyDeptDt;
    private String priorDeptDt;
    private BigDecimal tdySegreAmt;
}
